# Generated by Django 3.2.25 on 2026-02-21 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FuturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_after_graduation', models.CharField(max_length=100)),
                ('going_abroad', models.BooleanField()),
                ('preferred_country', models.CharField(blank=True, max_length=100, null=True)),
                ('career_goal_type', models.CharField(max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='future_plan', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_course', models.JSONField()),
                ('area_of_interest', models.JSONField()),
                ('skills_to_develop', models.JSONField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_interest', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_completed', models.BooleanField()),
                ('interested_in_internship', models.BooleanField()),
                ('have_certifications', models.BooleanField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_information', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_code', models.CharField(max_length=50)),
                ('department_course', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('year_of_study', models.CharField(max_length=20)),
                ('cgpa_percentage_range', models.CharField(max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_information', to='students.student')),
            ],
        ),
    ]
